spring:
  datasource:
    url: jdbc:mysql://43.139.115.202:3306/test_db_tenant?useSSL=false&autoReconnect=true&characterEncoding=utf8&AllowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出SQL Log; 方便debug