spring:
  datasource:
    url: jdbc:postgresql://43.139.115.202:5432/test_db_pg
    username: postgres
    password: 123456
mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl