spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db_liquibase?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  liquibase:
    enabled: true
    # \u5982\u4E0B\u914D\u7F6E\u662F\u88ABspring.datasource\u8D4B\u503C\u7684\uFF0C\u6240\u4EE5\u53EF\u4EE5\u4E0D\u914D\u7F6E
#    url: jdbc:mysql://localhost:3306/test_db_liquibase?useSSL=false&autoReconnect=true&characterEncoding=utf8
#    user: root
#    password: 123456
    change-log: classpath:/db/changelog/db.changelog-master.yaml