spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&autoReconnect=true&characterEncoding=utf8&AllowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.hubert.springboot.mysql57.mybatis.xml.entity
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    use-actual-param-name: true